server:
  port: 9000


spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:underdarks/config_repo.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAmPOc7k7XzCsaSC8kM20NRHaED4ZnLxI+ZN+J5qk7S2PJp4SH
            8dlOWrPl/L5MQhIzRnvbKmPiNFCBa+towhQzp+AT8RwJmjO+ydFk4vzZ7CCLZwMF
            U4FlIMKe1ENzwOA7+K6BMPJ5+gbKz7nRqzPSYyCk6kOLLdTPI1MwzrYYCpCAtd4P
            FcfNBLtSjDg1YD2qDJhtOrPzkLrDxIy44nIzOE75/CRlaadvEvV38yQ+1z/5fJQ1
            i6kfOXwYO6MuqST+OsgoM7CghG/VDmYdlj21F5Dm46Xka1X+UR2qcOCI5m6IusS6
            Dnqe+6ObJkSQq+7XcEuQpvkI+g1N1qeFqXxMvh61URpu0WFJxm6Lovf3E4KIsGci
            5fllRXx4uahqYGiGrfuwvRkfu+Zq72ayP3NkD1do4p5tOrMPVGqHWVEosbE5/Jfg
            iftppHnquiArrg3KSxfLOlHe8lu226yl8auXIFdmJrkoTE0tbzb6qDtwcM9qEC/n
            BR+mwRM90heGcrnqer3n0UhKVdc2X1nV47OyTEcv25gFPO8+PJljug/thXRqw6S0
            ABG/6btwm6m6QN1bXcddo1E1fKux2s6sPQLIZOj9ES7WFpNJs173DKFJJpOga4w4
            trA14iavEIi/rsKN4tjMVkTjY8jT54gFGURJra7Ke+03py9wDmLf7+7ACjcCAwEA
            AQKCAgBVoyDctTxSTlfazrpAKPDiwlDSuHgRfO9+X0LA6UQPxAFmT+gl23vpgQxm
            ZM4huDsJXdOqel5u2Bx+pkHzWIhLmETSHNarhgluylToWpZRhS9IMALNbIeIvi9b
            vaCT/3jUljAzjbAJ87+eavYgG1XStrZfjA3jTWHk73FGa+IuGBZYvcpIcaQy4Acq
            B1arWhtaDgYqdhMLl+aAqCHkd/iBsIZ7TI2TiHHCdboBYuvkbSdtPzZzye93qimP
            SqCXh+ToWKVZu61EObFa7IXoVwiL90+vanToPC+2jxudM7qy+nSHzho2fSWC02nN
            FVrDSWlKsKR/OLRz/Pr2Ernd2YDFnKcBKwKcufkM56a1oUjUqNR1uLzuHOryEJXX
            Z0uRUN/QiPidJajj/VFfVWdHNAomfScQNVitouzt7HDBSnoqxBy5YZVvy205MOKZ
            BDG+tuStUB7zLxSivCCPK2/57NaPKPMTl2ol4LyU3tJWLMMyqKbOUaHddfcivQVN
            SRKHY50OUwCJvST5OmZAzowwZgvT7JIMOEodItl7LrjGjkz5lqnbqPDyqJXtDeS7
            wo2p9bvTNLu291J0nPbRUCzqWp0B5hkn4kwWo/HCz5Fd8C//ohiQiQl4yG1k3D/r
            Oey3WJExVlAtFiPK5F9welW/i9IEW4ey7CBYqGW+w7gtKJBC4QKCAQEAx+t7vxZp
            60bRkgOl/IatYqA4Mcgjv/qPn+ZFW1od3pyVEaojiL/zoZiHb4LsnbIf/YVEzW3L
            hg7VwJU8N/xCRfyVYbqyuz7kwo4Nwyn960g74zD7W1W+ABAfQr/8WuZjHfDiUeFe
            yPQUZA/QeGs7ZkLa2lKNnLWXc5drV5ksF3hsjmLhKCSmzwwICkEr8COvt16DsMPY
            Q9Cvnt7qJUrW+l56pCdysJt+tPa+g40DVI6GylcS2wzDXKlWE8/hhOLKb52TgjzO
            LH3TCgqAta3EV8fPZT3FCrhoDaTTViMsVz2YYq6n/8gRN7xa0HxGAIhmHDulGmdp
            dFKdwWXnS+cQTwKCAQEAw9tGtnm2XMkgzyqsirUpLeU28NbvwTdenYSgcO41stv7
            E6BV9WjFSAkcuWxvO/2gqOU9UB6ZVM56/6C58CQRjbU5HzBk0GwhIxGJKu/kLQh0
            nK2Iv126P3h/9+DeqdWPz2JJep45Y1VDlPwGuIEFDMXEIO7gTS0Sp8/3RlNh6YGZ
            iUKu0Az4TgFErX5Crj+4XiiLquChri+1sVWZdqjSXfM1fW0eUKGqMV6oUC4S8Hlk
            lPhOYsEQ09SG25t/wnCL0MTKoU+Ps80uwOu6DYcY0zzDCu8nmrP7tj7jZVFcx0L+
            fU4k/u4F66VrlF7pGr/eetncz4aMcytX3hU+Tx5FmQKCAQEAqJEizzV767jT3hUb
            cPix23YSy87gbfA8B+wmUOeERf6rJrDZs2V+bKPqlpjDIBhgJuim4bwRHqEFlJOA
            qggWbWKTJktAhud6BZ23dvbCNg+7B052skVypiTx5ttwUcjujAFfIwEvZauAQfqf
            odlwxUHbvLhc1WS8Jefnx33MkqGkjs5K4Qk+aVfQs6zN+nZso+WajoIjqNKeMgvt
            S7J137eoGx9z8fu6c6WVb+CHjVV7y8JtkKuLUmcpwBzJH74GSOSJywewJA2X02CV
            tBqncgh1E/1oVii0+8QdugSAT7MM+TAhUWeFNQSpYh9W+v4HcwjLpp7JaR58C+T7
            iKF0uwKCAQBOv+kjz7Z6gkhV5BOyRftDv+kiV1nZd5jsfvo/zhf7TaYbkxlc7n58
            Y2WQTMBA/87Mejf38gW26rrb89UvcGE6eEZ6euvePcvpHNDpWcGGNeMlaEUWpOoR
            QTM7CMiewwbq3NssmVf7z7m3uso8/2t3YkFk+IdpoJjirqT/OuGgkQKaBRzi/IQO
            YUYq+Bx5kZdhDK5zy5RWxEoq/n8RDfpf2j2ErA5HX2leJnBIpO3qkPTXTSu/W1+X
            vNlojZKGLNia3bWXvLTMF9EXsvCBJfPeY40M5XIoKvwnoAuwnlFOsWpAGd6YPj5V
            LJMf+jWCEumyvcyiCLiKSkAvRJ1kFIjpAoIBAHJD7Vl5/sakNpance0JLFzT/xWe
            AZoer5gHIs2kX9GlbVlFvGfjSIrM/YNYJo4dn+ITEcuNDztOU/UOLoZh1CnuRa6B
            NQdmeMrZURGPLAnTV1kY0udI8RKwc+1Thn0LUKLHHT8kIhD958RnJes9/DB0/9tL
            U2i+CIJYvASdnak5vEO0lnOF4wGlGhu/ooQMofGbqq7+tkVMqsOSjaznVhDUSktb
            wE3ePfCR81T/nEkD1ch9x+VHxML/K+6TKfR1x2etG3sNgIAYQI4Da/9tov6gkl9i
            lqZ5FRRhNYw6luRT2Mn6jGTzrNLQ2cA+ZjFAYPZjFo4neYUxm2Bk0Nnfz04=
            -----END RSA PRIVATE KEY-----

