server:
  port: 9000


spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:underdarks/config_repo.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            본인 RSA값 복사
            -----END RSA PRIVATE KEY-----

